import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageInitializer from "@/LanguageInitializer";
import Toaster from "./components/organisms/toaster/Toaster";
import GlobalReduxProvider from "@/Providers/GlobalReduxProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SCOUT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <GlobalReduxProvider>
            <Toaster />
            <LanguageInitializer />

            {children}
          </GlobalReduxProvider>
      </body>
    </html>
  );
}
