import {
  GppGoodOutlined as GppGoodOutlinedIcon,
  VisibilityOutlined as VisibilityOutlinedIcon,
  GroupsOutlined as GroupsOutlinedIcon,
  InsightsOutlined as InsightsOutlinedIcon,
  VideocamOffOutlined as VideocamOffOutlinedIcon,
  HealthAndSafetyOutlined as HealthAndSafetyOutlinedIcon,
  LocalFireDepartmentOutlined as LocalFireDepartmentOutlinedIcon,
  AccessibilityNewOutlined as AccessibilityNewOutlinedIcon,
  LocalShippingOutlined as LocalShippingOutlinedIcon,
  DoorFrontOutlined as DoorFrontOutlinedIcon,
  Diversity3Outlined as Diversity3OutlinedIcon,
  SensorsOutlined as SensorsOutlinedIcon,
  DarkModeOutlined as DarkModeOutlinedIcon,
  NoAccountsOutlined as NoAccountsOutlinedIcon,
  HourglassBottomOutlined as HourglassBottomOutlinedIcon,
  PersonPinCircleOutlined as PersonPinCircleOutlinedIcon,
  BlockOutlined as BlockOutlinedIcon,
  PhoneAndroidOutlined as PhoneAndroidOutlinedIcon,
  AirlineSeatIndividualSuiteOutlined as AirlineSeatIndividualSuiteOutlinedIcon,
  PeopleAltOutlined as PeopleAltOutlinedIcon,
  DirectionsCarOutlined as DirectionsCarOutlinedIcon,
  RestaurantOutlined as RestaurantOutlinedIcon,
  WarehouseOutlined as WarehouseOutlinedIcon,
  NoCrashOutlined as NoCrashOutlinedIcon,
  FaceOutlined as FaceOutlinedIcon,
  FaceRetouchingNaturalOutlined as FaceRetouchingNaturalOutlinedIcon,
  ManageAccountsOutlined as ManageAccountsOutlinedIcon,
  MapOutlined as MapOutlinedIcon,
  VideocamOutlined as VideocamOutlinedIcon,
  WidgetsOutlined as WidgetsOutlinedIcon,
} from "@mui/icons-material";
import { FEATURE } from "./featureRegistry";
import { MuiIcon } from "./dashboardTheme";

/** Icon per featureId — shared between the Sidebar and the Dashboard's AI
 *  Use Cases Status tiles, so the same feature always shows the same icon. */
export const FEATURE_ICON: Record<string, MuiIcon> = {
  [FEATURE.SAFETY_COMPLIANCE]: GppGoodOutlinedIcon,
  [FEATURE.SURVEILLANCE_MONITORING]: VisibilityOutlinedIcon,
  [FEATURE.WORKFORCE_MONITORING]: GroupsOutlinedIcon,
  [FEATURE.OPERATIONAL_INSIGHTS]: InsightsOutlinedIcon,
  [FEATURE.CAMERA_TAMPERING]: VideocamOffOutlinedIcon,
  [FEATURE.PPE_DETECTION]: HealthAndSafetyOutlinedIcon,
  [FEATURE.FIRE_SMOKE]: LocalFireDepartmentOutlinedIcon,
  [FEATURE.FALL_DETECTION]: AccessibilityNewOutlinedIcon,
  [FEATURE.OBJECT_DETECTION]: LocalShippingOutlinedIcon,
  [FEATURE.EMERGENCY_EXIT_BLOCKAGE]: DoorFrontOutlinedIcon,
  [FEATURE.CROWD_DETECTION]: Diversity3OutlinedIcon,
  [FEATURE.INTRUSION_DETECTION]: SensorsOutlinedIcon,
  [FEATURE.MOVEMENT_DURING_SHUTDOWN_HOUR]: DarkModeOutlinedIcon,
  [FEATURE.UNAUTHORIZED_ACCESS]: NoAccountsOutlinedIcon,
  [FEATURE.EMPLOYEE_IDLE_TIME]: HourglassBottomOutlinedIcon,
  [FEATURE.EMPLOYEE_PRESENCE_CRITICAL_AREA]: PersonPinCircleOutlinedIcon,
  [FEATURE.EMPLOYEE_PRESENCE_RESTRICTED_AREA]: BlockOutlinedIcon,
  [FEATURE.MOBILE_PHONE_USAGE]: PhoneAndroidOutlinedIcon,
  [FEATURE.SLEEPING_SECURITY_PERSONNEL]: AirlineSeatIndividualSuiteOutlinedIcon,
  [FEATURE.PEOPLE_COUNT]: PeopleAltOutlinedIcon,
  [FEATURE.VEHICLE_COUNT]: DirectionsCarOutlinedIcon,
  [FEATURE.CANTEEN_USAGE]: RestaurantOutlinedIcon,
  [FEATURE.VEHICLE_UNLOADING_LOADING]: WarehouseOutlinedIcon,
  [FEATURE.UNAUTHORIZED_PARKING]: NoCrashOutlinedIcon,
  [FEATURE.FACE_RECOGNITION]: FaceOutlinedIcon,
  [FEATURE.FACE_IDLE_MONITORING]: FaceRetouchingNaturalOutlinedIcon,
  [FEATURE.ROLE_MANAGEMENT]: ManageAccountsOutlinedIcon,
  [FEATURE.USER_MANAGEMENT]: PeopleAltOutlinedIcon,
  [FEATURE.ZONE_LOCATION_MAPPING]: MapOutlinedIcon,
  [FEATURE.CAMERA_MANAGEMENT]: VideocamOutlinedIcon,
  [FEATURE.USE_CASE_MANAGER]: WidgetsOutlinedIcon,
};
